version: '3'
services:
  shortened-url-microservice:
    build: .
    ports:
      - "3000:3000"
    networks:
      - shortened-url-network

networks:
  shortened-url-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16